version: "3.5"

x-services-volume:
  &services-volume
  type: bind
  source: ./data
  target: /testing-labeling/data

services:
  labeling:
    container_name: asl
    build: 
      context: testing-l
      dockerfile: Dockerfile
    command: "label-studio start labeling/newspaper_labeling --port 8080 --log-level DEBUG"
    ports: 
      - 8080:8080
    depends_on:
      - modeling
    restart: always
    volumes: 
      - *services-volume
  modeling:
    container_name: asm
    build: 
      context: testing-m
      dockerfile: Dockerfile
    command: "label-studio-ml start labeling/var_backend --port 9090"
    ports: 
      - 9090:9090
    restart: always
    volumes: 
      - *services-volume