version: "3"

services:
  labeling:
    container_name: asl
    build: 
      context: testing-l
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - modeling
    restart: always
    volumes:
    - ./data:/testing-labeling/data
    command: "label-studio start labeling/newspaper_labeling --port 8080 --log-level DEBUG"
  modeling:
    container_name: asm
    build: 
      context: testing-m
      dockerfile: Dockerfile
    ports: 
      - 9090:9090
    restart: always
    volumes:
    - ./data:/testing-modeling/data
    command: "label-studio-ml start labeling/var_backend --port 9090"